Repository Wynntils/Wynntils, pull requests merged in 2018-12, with the labels that each got.

#15 Prevent closing loot chests that contain mythic items
  src/main/java/cf/wynntils/core/utils/Utils.java
  src/main/java/cf/wynntils/modules/utilities/configs/UtilitiesConfig.java
  src/main/java/cf/wynntils/modules/utilities/events/ClientEvents.java
  src/main/java/cf/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
  src/main/java/cf/wynntils/modules/utilities/overlays/inventories/SkillPointOverlay.java
Labels: Enhancement

#16 Fix an issue with the armor rarity overlay being misaligned when <4 pieces require it
  src/main/java/cf/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
Labels: Bug

#17 Add basic powder highlighting
  src/main/java/cf/wynntils/modules/utilities/configs/UtilitiesConfig.java
  src/main/java/cf/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
Labels: Enhancement

#20 Add right clicking on a quest to open on wiki
  src/main/java/cf/wynntils/modules/questbook/overlays/ui/QuestBookGUI.java
Labels: Enhancement

#25 Fixed typos/grammar issues and adds consistency
  src/main/java/cf/wynntils/modules/utilities/configs/OverlayConfig.java
Labels: Translation Fix
