Repository Wynntils/Wynntils, pull requests merged in 2025-08, with the labels that each got.

#3382 fix: parse bomb bell message
  common/src/main/java/com/wynntils/features/chat/BombBellRelayFeature.java
  common/src/main/java/com/wynntils/models/worlds/BombModel.java
  fabric/src/test/java/TestRegex.java
Labels: 2.1.3

#3402 fix: revert Fabric API version
  gradle.properties
Labels: release

#3414 fix: Fix hide info and party finder messages
  common/src/main/java/com/wynntils/features/chat/MessageFilterFeature.java
  fabric/src/test/java/TestRegex.java
Labels: 2.1.3

#3410 feat: Support raid reward chest rerolls
  common/src/main/java/com/wynntils/models/containers/containers/RaidRewardChestContainer.java
  common/src/main/java/com/wynntils/models/raid/RaidModel.java
Labels: 2.1.3

#3409 fix: Fix challenge completed and failed patterns
  common/src/main/java/com/wynntils/models/lootrun/LootrunModel.java
  common/src/main/java/com/wynntils/models/raid/RaidModel.java
Labels: 2.1.3

#3415 fix: Insert space when unwrapping
  common/src/main/java/com/wynntils/models/trademarket/TradeMarketModel.java
  common/src/main/java/com/wynntils/models/worlds/BombModel.java
  common/src/main/java/com/wynntils/utils/mc/StyledTextUtils.java
  fabric/src/test/java/TestRegex.java
Labels: 2.1.3

#3417 fix: Use proper colour for crimson beacons
  common/src/main/java/com/wynntils/models/lootrun/beacons/LootrunBeaconKind.java
  common/src/main/java/com/wynntils/overlays/lootrun/LootrunBeaconCountOverlay.java
  common/src/main/java/com/wynntils/overlays/lootrun/LootrunTaskNameOverlay.java
Labels: release

#3423 feat: Annotate store items
  common/src/main/java/com/wynntils/core/persisted/upfixers/UpfixerManager.java
  common/src/main/java/com/wynntils/core/persisted/upfixers/config/ItemHighlightFeatureCosmeticToStoreUpfixer.java
  common/src/main/java/com/wynntils/features/inventory/ItemHighlightFeature.java
  common/src/main/java/com/wynntils/models/items/ItemModel.java
  common/src/main/java/com/wynntils/models/items/annotators/gui/CosmeticTierAnnotator.java
  common/src/main/java/com/wynntils/models/items/annotators/gui/StoreTierAnnotator.java
  common/src/main/java/com/wynntils/models/items/items/gui/StoreItem.java
  common/src/main/resources/assets/wynntils/lang/de_de.json
  common/src/main/resources/assets/wynntils/lang/en_us.json
  common/src/main/resources/assets/wynntils/lang/es_es.json
  common/src/main/resources/assets/wynntils/lang/fr_fr.json
  common/src/main/resources/assets/wynntils/lang/hu_hu.json
  common/src/main/resources/assets/wynntils/lang/it_it.json
  common/src/main/resources/assets/wynntils/lang/ja_jp.json
  common/src/main/resources/assets/wynntils/lang/ko_kr.json
  common/src/main/resources/assets/wynntils/lang/nl_nl.json
  common/src/main/resources/assets/wynntils/lang/pl_pl.json
  common/src/main/resources/assets/wynntils/lang/pt_pt.json
  common/src/main/resources/assets/wynntils/lang/ru_ru.json
  common/src/main/resources/assets/wynntils/lang/sv_se.json
  common/src/main/resources/assets/wynntils/lang/zh_cn.json
  common/src/main/resources/assets/wynntils/lang/zh_tw.json
Labels: 2.1.3

#3425 fix: Fix element font handling in abbreviate mob health and focused mob overlay
  common/src/main/java/com/wynntils/features/combat/AbbreviateMobHealthFeature.java
  common/src/main/java/com/wynntils/models/combat/CombatModel.java
  common/src/main/java/com/wynntils/models/combat/bossbar/DamageBar.java
  common/src/main/java/com/wynntils/models/combat/type/FocusedDamageEvent.java
  common/src/main/java/com/wynntils/models/combat/type/MobElementals.java
  common/src/main/java/com/wynntils/overlays/gamebars/FocusedMobHealthBarOverlay.java
  common/src/main/java/com/wynntils/utils/StringUtils.java
  common/src/main/resources/assets/wynntils/lang/en_us.json
  fabric/src/test/java/TestRegex.java
Labels: release, 2.1.3

#3333 feat: Update MapData locations, add dungeon merchants
  common/src/main/java/com/wynntils/services/mapdata/features/builtin/ServiceLocation.java
  common/src/main/resources/assets/wynntils/urls.json
Labels: mapdata

#3474 fix: Connect to Hades on separate thread and broaden exception handling
  common/src/main/java/com/wynntils/services/hades/HadesService.java
Labels: release
